_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
apply_attention:
    value: false
beam_size:
    value: 1
decoder_name:
    value: GRU
decoder_num_layers:
    value: 2
dropout_p:
    value: 0.2
embedding_size:
    value: 256
encoder_bidirectional:
    value: true
encoder_name:
    value: RNN
encoder_num_layers:
    value: 2
hidden_size:
    value: 128
learning_rate:
    value: 0.001
teacher_forcing_p:
    value: 0.8
