wandb_version: 1

apply_attention:
  value: false
beam_size:
  value: 1
decoder_name:
  value: RNN
decoder_num_layers:
  value: 2
dropout_p:
  value: 0.2
embedding_size:
  value: 256
encoder_bidirectional:
  value: true
encoder_name:
  value: GRU
encoder_num_layers:
  value: 2
hidden_size:
  value: 128
learning_rate:
  value: 0.003
teacher_forcing_p:
  value: 0.8
